### PR TITLE
Fix gif in readme

### PR DESCRIPTION
**Pull request by daevski**
New GIF for the README that correctly represents the script output and other minor README edits.

### CODE REVIEW

**Comment by amiechen** [comment]
@daevski I will merge the PR once the conflict is resolved, just let me know!

**Comment by daevski** [comment]
I can't seem to "see" the conflicts locally; If fresh clone my repo, and pull my 'Fix_GIF_readme' branch, then pull your master branch from your repo, I see no merge conflicts. 
image

And here on the GitHub pull request, I only see this image:
image

Can you let me know what the specific conflicts are? 

1. I see batchloader.gif is a conflict (which I've deleted on my end, but it might also think it's a rename from batchloader.gif -> example.gif ?) 
1. And the readme.md file is listed as having conflicts, but I can't see what they are. 

Thanks,
David

**Comment by daevski** [comment]
Looks excellent! :+1:

**Comment by amiechen** [comment]
hey @daevski sorry for my delayed reply, was in the middle of a move.

I resolved the conflict and merged your changes in. Thanks again for all the good work!

**Pull request merged**
